/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGR


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif


/* -----------------------------------------------------------------------------
 * swigrun.swg
 *
 * This file contains generic C API SWIG runtime support for pointer
 * type checking.
 * ----------------------------------------------------------------------------- */

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "4"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
# define SWIG_QUOTE_STRING(x) #x
# define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
# define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
# define SWIG_TYPE_TABLE_NAME
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the SWIG runtime code.
  In 99.9% of the cases, SWIG just needs to declare them as 'static'.
  
  But only do this if strictly necessary, ie, if you have problems
  with your compiler or suchlike.
*/

#ifndef SWIGRUNTIME
# define SWIGRUNTIME SWIGINTERN
#endif

#ifndef SWIGRUNTIMEINLINE
# define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

/*  Generic buffer size */
#ifndef SWIG_BUFFER_SIZE
# define SWIG_BUFFER_SIZE 1024
#endif

/* Flags for pointer conversions */
#define SWIG_POINTER_DISOWN        0x1
#define SWIG_CAST_NEW_MEMORY       0x2

/* Flags for new pointer objects */
#define SWIG_POINTER_OWN           0x1


/* 
   Flags/methods for returning states.
   
   The SWIG conversion methods, as ConvertPtr, return and integer 
   that tells if the conversion was successful or not. And if not,
   an error code can be returned (see swigerrors.swg for the codes).
   
   Use the following macros/flags to set or process the returning
   states.
   
   In old versions of SWIG, code such as the following was usually written:

     if (SWIG_ConvertPtr(obj,vptr,ty.flags) != -1) {
       // success code
     } else {
       //fail code
     }

   Now you can be more explicit:

    int res = SWIG_ConvertPtr(obj,vptr,ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
    } else {
      // fail code
    }

   which is the same really, but now you can also do

    Type *ptr;
    int res = SWIG_ConvertPtr(obj,(void **)(&ptr),ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
      if (SWIG_IsNewObj(res) {
        ...
	delete *ptr;
      } else {
        ...
      }
    } else {
      // fail code
    }
    
   I.e., now SWIG_ConvertPtr can return new objects and you can
   identify the case and take care of the deallocation. Of course that
   also requires SWIG_ConvertPtr to return new result values, such as

      int SWIG_ConvertPtr(obj, ptr,...) {         
        if (<obj is ok>) {			       
          if (<need new object>) {		       
            *ptr = <ptr to new allocated object>; 
            return SWIG_NEWOBJ;		       
          } else {				       
            *ptr = <ptr to old object>;	       
            return SWIG_OLDOBJ;		       
          } 				       
        } else {				       
          return SWIG_BADOBJ;		       
        }					       
      }

   Of course, returning the plain '0(success)/-1(fail)' still works, but you can be
   more explicit by returning SWIG_BADOBJ, SWIG_ERROR or any of the
   SWIG errors code.

   Finally, if the SWIG_CASTRANK_MODE is enabled, the result code
   allows to return the 'cast rank', for example, if you have this

       int food(double)
       int fooi(int);

   and you call
 
      food(1)   // cast rank '1'  (1 -> 1.0)
      fooi(1)   // cast rank '0'

   just use the SWIG_AddCast()/SWIG_CheckState()
*/

#define SWIG_OK                    (0) 
#define SWIG_ERROR                 (-1)
#define SWIG_IsOK(r)               (r >= 0)
#define SWIG_ArgError(r)           ((r != SWIG_ERROR) ? r : SWIG_TypeError)  

/* The CastRankLimit says how many bits are used for the cast rank */
#define SWIG_CASTRANKLIMIT         (1 << 8)
/* The NewMask denotes the object was created (using new/malloc) */
#define SWIG_NEWOBJMASK            (SWIG_CASTRANKLIMIT  << 1)
/* The TmpMask is for in/out typemaps that use temporal objects */
#define SWIG_TMPOBJMASK            (SWIG_NEWOBJMASK << 1)
/* Simple returning values */
#define SWIG_BADOBJ                (SWIG_ERROR)
#define SWIG_OLDOBJ                (SWIG_OK)
#define SWIG_NEWOBJ                (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ                (SWIG_OK | SWIG_TMPOBJMASK)
/* Check, add and del mask methods */
#define SWIG_AddNewMask(r)         (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r)           (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r)         (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r)           (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))

/* Cast-Rank Mode */
#if defined(SWIG_CASTRANK_MODE)
#  ifndef SWIG_TypeRank
#    define SWIG_TypeRank             unsigned long
#  endif
#  ifndef SWIG_MAXCASTRANK            /* Default cast allowed */
#    define SWIG_MAXCASTRANK          (2)
#  endif
#  define SWIG_CASTRANKMASK          ((SWIG_CASTRANKLIMIT) -1)
#  define SWIG_CastRank(r)           (r & SWIG_CASTRANKMASK)
SWIGINTERNINLINE int SWIG_AddCast(int r) { 
  return SWIG_IsOK(r) ? ((SWIG_CastRank(r) < SWIG_MAXCASTRANK) ? (r + 1) : SWIG_ERROR) : r;
}
SWIGINTERNINLINE int SWIG_CheckState(int r) { 
  return SWIG_IsOK(r) ? SWIG_CastRank(r) + 1 : 0; 
}
#else /* no cast-rank mode */
#  define SWIG_AddCast
#  define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#endif


#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *, int *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

/* Structure to store information on one type */
typedef struct swig_type_info {
  const char             *name;			/* mangled name of this type */
  const char             *str;			/* human readable name of this type */
  swig_dycast_func        dcast;		/* dynamic cast function down a hierarchy */
  struct swig_cast_info  *cast;			/* linked list of types that can cast into this type */
  void                   *clientdata;		/* language specific type data */
  int                    owndata;		/* flag if the structure owns the clientdata */
} swig_type_info;

/* Structure to store a type and conversion function used for casting */
typedef struct swig_cast_info {
  swig_type_info         *type;			/* pointer to type that is equivalent to this type */
  swig_converter_func     converter;		/* function to cast the void pointers */
  struct swig_cast_info  *next;			/* pointer to next cast in linked list */
  struct swig_cast_info  *prev;			/* pointer to the previous cast */
} swig_cast_info;

/* Structure used to store module information
 * Each module generates one structure like this, and the runtime collects
 * all of these structures and stores them in a circularly linked list.*/
typedef struct swig_module_info {
  swig_type_info         **types;		/* Array of pointers to swig_type_info structures that are in this module */
  size_t                 size;		        /* Number of types in this module */
  struct swig_module_info *next;		/* Pointer to next element in circularly linked list */
  swig_type_info         **type_initial;	/* Array of initially generated type structures */
  swig_cast_info         **cast_initial;	/* Array of initially generated casting structures */
  void                    *clientdata;		/* Language specific module data */
} swig_module_info;

/* 
  Compare two type names skipping the space characters, therefore
  "char*" == "char *" and "Class<int>" == "Class<int >", etc.

  Return 0 when the two name types are equivalent, as in
  strncmp, but skipping ' '.
*/
SWIGRUNTIME int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return (*f1 > *f2) ? 1 : -1;
  }
  return (int)((l1 - f1) - (l2 - f2));
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if not equal, 1 if equal
*/
SWIGRUNTIME int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  int equiv = 0;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (!equiv && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = (SWIG_TypeNameComp(nb, ne, tb, te) == 0) ? 1 : 0;
    if (*ne) ++ne;
  }
  return equiv;
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if equal, -1 if nb < tb, 1 if nb > tb
*/
SWIGRUNTIME int
SWIG_TypeCompare(const char *nb, const char *tb) {
  int equiv = 0;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (!equiv && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = (SWIG_TypeNameComp(nb, ne, tb, te) == 0) ? 1 : 0;
    if (*ne) ++ne;
  }
  return equiv;
}


/*
  Check the typename
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheck(const char *c, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (strcmp(iter->type->name, c) == 0) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/* 
  Identical to SWIG_TypeCheck, except strcmp is replaced with a pointer comparison
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheckStruct(swig_type_info *from, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *iter = ty->cast;
    while (iter) {
      if (iter->type == from) {
        if (iter == ty->cast)
          return iter;
        /* Move iter to the top of the linked list */
        iter->prev->next = iter->next;
        if (iter->next)
          iter->next->prev = iter->prev;
        iter->next = ty->cast;
        iter->prev = 0;
        if (ty->cast) ty->cast->prev = iter;
        ty->cast = iter;
        return iter;
      }
      iter = iter->next;
    }
  }
  return 0;
}

/*
  Cast a pointer up an inheritance hierarchy
*/
SWIGRUNTIMEINLINE void *
SWIG_TypeCast(swig_cast_info *ty, void *ptr, int *newmemory) {
  return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr, newmemory);
}

/* 
   Dynamic pointer casting. Down an inheritance hierarchy
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/*
  Return the name associated with this type
*/
SWIGRUNTIMEINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/*
  Return the pretty name associated with this type,
  that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (!type) return NULL;
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/* 
   Set the clientdata field for a type
*/
SWIGRUNTIME void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_cast_info *cast = ti->cast;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;
  
  while (cast) {
    if (!cast->converter) {
      swig_type_info *tc = cast->type;
      if (!tc->clientdata) {
	SWIG_TypeClientData(tc, clientdata);
      }
    }    
    cast = cast->next;
  }
}
SWIGRUNTIME void
SWIG_TypeNewClientData(swig_type_info *ti, void *clientdata) {
  SWIG_TypeClientData(ti, clientdata);
  ti->owndata = 1;
}
  
/*
  Search for a swig_type_info structure only by mangled name
  Search is a O(log #types)
  
  We start searching at module start, and finish searching when start == end.  
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_MangledTypeQueryModule(swig_module_info *start, 
                            swig_module_info *end, 
		            const char *name) {
  swig_module_info *iter = start;
  do {
    if (iter->size) {
      register size_t l = 0;
      register size_t r = iter->size - 1;
      do {
	/* since l+r >= 0, we can (>> 1) instead (/ 2) */
	register size_t i = (l + r) >> 1; 
	const char *iname = iter->types[i]->name;
	if (iname) {
	  register int compare = strcmp(name, iname);
	  if (compare == 0) {	    
	    return iter->types[i];
	  } else if (compare < 0) {
	    if (i) {
	      r = i - 1;
	    } else {
	      break;
	    }
	  } else if (compare > 0) {
	    l = i + 1;
	  }
	} else {
	  break; /* should never happen */
	}
      } while (l <= r);
    }
    iter = iter->next;
  } while (iter != end);
  return 0;
}

/*
  Search for a swig_type_info structure for either a mangled name or a human readable name.
  It first searches the mangled names of the types, which is a O(log #types)
  If a type is not found it then searches the human readable names, which is O(#types).
  
  We start searching at module start, and finish searching when start == end.  
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeQueryModule(swig_module_info *start, 
                     swig_module_info *end, 
		     const char *name) {
  /* STEP 1: Search the name field using binary search */
  swig_type_info *ret = SWIG_MangledTypeQueryModule(start, end, name);
  if (ret) {
    return ret;
  } else {
    /* STEP 2: If the type hasn't been found, do a complete search
       of the str field (the human readable name) */
    swig_module_info *iter = start;
    do {
      register size_t i = 0;
      for (; i < iter->size; ++i) {
	if (iter->types[i]->str && (SWIG_TypeEquiv(iter->types[i]->str, name)))
	  return iter->types[i];
      }
      iter = iter->next;
    } while (iter != end);
  }
  
  /* neither found a match */
  return 0;
}

/* 
   Pack binary data into a string
*/
SWIGRUNTIME char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static const char hex[17] = "0123456789abcdef";
  register const unsigned char *u = (unsigned char *) ptr;
  register const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    register unsigned char uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* 
   Unpack binary data from a string
*/
SWIGRUNTIME const char *
SWIG_UnpackData(const char *c, void *ptr, size_t sz) {
  register unsigned char *u = (unsigned char *) ptr;
  register const unsigned char *eu = u + sz;
  for (; u != eu; ++u) {
    register char d = *(c++);
    register unsigned char uu;
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    else 
      return (char *) 0;
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    else 
      return (char *) 0;
    *u = uu;
  }
  return c;
}

/* 
   Pack 'void *' into a string buffer.
*/
SWIGRUNTIME char *
SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz) {
  char *r = buff;
  if ((2*sizeof(void *) + 2) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,&ptr,sizeof(void *));
  if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
  strcpy(r,name);
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      *ptr = (void *) 0;
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sizeof(void *));
}

SWIGRUNTIME char *
SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz) {
  char *r = buff;
  size_t lname = (name ? strlen(name) : 0);
  if ((2*sz + 2 + lname) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  if (lname) {
    strncpy(r,name,lname+1);
  } else {
    *r = 0;
  }
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      memset(ptr,0,sz);
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sz);
}

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

/* Remove global namespace pollution */
#if !defined(SWIG_NO_R_NO_REMAP)
# define R_NO_REMAP
#endif
#if !defined(SWIG_NO_STRICT_R_HEADERS)
# define STRICT_R_HEADERS
#endif

#include <Rdefines.h>
#include <Rversion.h>
#include <stdlib.h>
#include <assert.h>

#if R_VERSION >= R_Version(2,6,0)
#define VMAXTYPE void *
#else
#define VMAXTYPE char *
#endif

/*
  This is mainly a way to avoid having lots of local variables that may 
  conflict with those in the routine.

   Change name to R_SWIG_Callb....
*/
typedef struct RCallbackFunctionData {

  SEXP fun;
  SEXP userData;


  SEXP expr;
  SEXP retValue;
  int errorOccurred;

  SEXP el;  /* Temporary pointer used in the construction of the expression to call the R function. */

  struct RCallbackFunctionData *previous;   /* Stack */

} RCallbackFunctionData;

static RCallbackFunctionData  *callbackFunctionDataStack;


SWIGRUNTIME SEXP
R_SWIG_debug_getCallbackFunctionData()
{
  int n, i;
  SEXP ans;
  RCallbackFunctionData  *p = callbackFunctionDataStack;

  n = 0;
  while(p) { 
    n++;
    p = p->previous;
  }

  Rf_protect(ans = Rf_allocVector(VECSXP, n));
  for(p = callbackFunctionDataStack, i = 0; i < n; p = p->previous, i++) 
      SET_VECTOR_ELT(ans, i, p->fun);

  Rf_unprotect(1);

  return(ans);
}



SWIGRUNTIME RCallbackFunctionData *
R_SWIG_pushCallbackFunctionData(SEXP fun, SEXP userData)
{
   RCallbackFunctionData *el;
   el = (RCallbackFunctionData *) calloc(1, sizeof(RCallbackFunctionData));
   el->fun = fun;
   el->userData = userData;
   el->previous = callbackFunctionDataStack;

   callbackFunctionDataStack = el;

   return(el);
}


SWIGRUNTIME SEXP
R_SWIG_R_pushCallbackFunctionData(SEXP fun, SEXP userData)
{
    R_SWIG_pushCallbackFunctionData(fun, userData);
    return R_NilValue;
}

SWIGRUNTIME RCallbackFunctionData *
R_SWIG_getCallbackFunctionData()
{
  if(!callbackFunctionDataStack) {
    Rf_error("Supposedly impossible error occurred in the SWIG callback mechanism."
            "  No callback function data set.");
  }
  
  return callbackFunctionDataStack;
}

SWIGRUNTIME void
R_SWIG_popCallbackFunctionData(int doFree)
{
  RCallbackFunctionData  *el = NULL;
  if(!callbackFunctionDataStack)
    return ; /* Error !!! */

  el = callbackFunctionDataStack ;
  callbackFunctionDataStack = callbackFunctionDataStack->previous;

  if(doFree)
     free(el);
}


/*
  Interface to S function
      is(obj, type)
  which is to be used to determine if an 
  external pointer inherits from the right class.

  Ideally, we would like to be able to do this without an explicit call to the is() function.
  When the S4 class system uses its own SEXP types, then we will hopefully be able to do this
  in the C code.

  Should we make the expression static and preserve it to avoid the overhead of 
  allocating each time.
*/
SWIGRUNTIME int
R_SWIG_checkInherits(SEXP obj, SEXP tag, const char *type)
{
  SEXP e, val;
  int check_err = 0;

  Rf_protect(e = Rf_allocVector(LANGSXP, 3));
  SETCAR(e, Rf_install("extends"));

  SETCAR(CDR(e), Rf_mkString(CHAR(PRINTNAME(tag))));
  SETCAR(CDR(CDR(e)), Rf_mkString(type));

  val = R_tryEval(e, R_GlobalEnv, &check_err);
  Rf_unprotect(1);
  if(check_err) 
    return(0);


  return(LOGICAL(val)[0]);
}


SWIGRUNTIME void *
R_SWIG_resolveExternalRef(SEXP arg, const char * const type, const char * const argName, Rboolean nullOk)
{
  void *ptr;
  SEXP orig = arg;

  if(TYPEOF(arg) != EXTPTRSXP) 
    arg = GET_SLOT(arg, Rf_mkString("ref"));

  
  if(TYPEOF(arg) != EXTPTRSXP) {
    Rf_error("argument %s must be an external pointer (from an ExternalReference)", argName);
  }


  ptr = R_ExternalPtrAddr(arg);

  if(ptr == NULL && nullOk == (Rboolean) FALSE) {
    Rf_error("the external pointer (of type %s) for argument %s has value NULL", argName, type);
  }

  if(type[0] && R_ExternalPtrTag(arg) != Rf_install(type) && strcmp(type, "voidRef")
      && !R_SWIG_checkInherits(orig,  R_ExternalPtrTag(arg), type)) {
    Rf_error("the external pointer for argument %s has tag %s, not the expected value %s",
             argName, CHAR(PRINTNAME(R_ExternalPtrTag(arg))), type);
  }


  return(ptr);
}

SWIGRUNTIME void
R_SWIG_ReferenceFinalizer(SEXP el)
{
  void *ptr = R_SWIG_resolveExternalRef(el, "", "<finalizer>",  (Rboolean) 1);
  fprintf(stderr, "In R_SWIG_ReferenceFinalizer for %p\n", ptr);
  Rf_PrintValue(el);

  if(ptr) {
     if(TYPEOF(el) != EXTPTRSXP)
        el = GET_SLOT(el, Rf_mkString("ref"));

     if(TYPEOF(el) == EXTPTRSXP)
        R_ClearExternalPtr(el);

     free(ptr);
  }

  return;
}

typedef enum {R_SWIG_EXTERNAL, R_SWIG_OWNER } R_SWIG_Owner;

SWIGRUNTIME SEXP
SWIG_MakePtr(void *ptr, const char *typeName, R_SWIG_Owner owner)
{
  SEXP external, r_obj;
  const char *p = typeName;

  if(typeName[0] == '_')
     p = typeName + 1;

  Rf_protect(external = R_MakeExternalPtr(ptr, Rf_install(typeName), R_NilValue));
  Rf_protect(r_obj = NEW_OBJECT(MAKE_CLASS((char *) typeName)));

  if(owner)
    R_RegisterCFinalizer(external, R_SWIG_ReferenceFinalizer);

  r_obj = SET_SLOT(r_obj, Rf_mkString((char *) "ref"), external);
  SET_S4_OBJECT(r_obj);
  Rf_unprotect(2);

  return(r_obj);
}


SWIGRUNTIME SEXP
R_SWIG_create_SWIG_R_Array(const char *typeName, SEXP ref, int len)
{
   SEXP arr;

/*XXX remove the char * cast when we can. MAKE_CLASS should be declared appropriately. */
   Rf_protect(arr = NEW_OBJECT(MAKE_CLASS((char *) typeName)));
   Rf_protect(arr = R_do_slot_assign(arr, Rf_mkString("ref"), ref));
   Rf_protect(arr = R_do_slot_assign(arr, Rf_mkString("dims"), Rf_ScalarInteger(len)));

   Rf_unprotect(3); 			   
   SET_S4_OBJECT(arr);	
   return arr;
}

#define ADD_OUTPUT_ARG(result, pos, value, name)  r_ans = AddOutputArgToReturn(pos, value, name, OutputValues);

SWIGRUNTIME SEXP
AddOutputArgToReturn(int pos, SEXP value, const char *name, SEXP output)
{
  SET_VECTOR_ELT(output, pos, value);

  return(output);
}

/* Create a new pointer object */
SWIGRUNTIMEINLINE SEXP
SWIG_R_NewPointerObj(void *ptr, swig_type_info *type, int flags) {
  SEXP rptr = R_MakeExternalPtr(ptr, 
  R_MakeExternalPtr(type, R_NilValue, R_NilValue), R_NilValue); 
  SET_S4_OBJECT(rptr);
//  rptr = Rf_setAttrib(rptr, R_ClassSymbol, mkChar(SWIG_TypeName(type)));
  return rptr;
}

/* Convert a pointer value */
SWIGRUNTIMEINLINE int
SWIG_R_ConvertPtr(SEXP obj, void **ptr, swig_type_info *ty, int flags) {
  void *vptr;
  if (!obj) return SWIG_ERROR;
  if (obj == R_NilValue) {
    if (ptr) *ptr = NULL;
    return SWIG_OK;
  }

  vptr = R_ExternalPtrAddr(obj);
  if (ty) {
    swig_type_info *to = (swig_type_info*) 
      R_ExternalPtrAddr(R_ExternalPtrTag(obj));
    if (to == ty) {
      if (ptr) *ptr = vptr;
    } else {
      swig_cast_info *tc = SWIG_TypeCheck(to->name,ty);
      int newmemory = 0;
      if (ptr) *ptr = SWIG_TypeCast(tc,vptr,&newmemory);
      assert(!newmemory); /* newmemory handling not yet implemented */
    }
  } else {
      if (ptr) *ptr = vptr;
 }
  return SWIG_OK;
}

SWIGRUNTIME swig_module_info *
SWIG_GetModule(void *v) {
  static void *type_pointer = (void *)0;
  return (swig_module_info *) type_pointer;
}

SWIGRUNTIME void
SWIG_SetModule(void *v, swig_module_info *swig_module) {
}

typedef struct {
  void *pack;
  swig_type_info *ty;
  size_t size;
} RSwigPacked;

/* Create a new packed object */

SWIGRUNTIMEINLINE SEXP RSwigPacked_New(void *ptr, size_t sz,
		  swig_type_info *ty) {
  SEXP rptr;
  RSwigPacked *sobj = 
  (RSwigPacked*) malloc(sizeof(RSwigPacked));
  if (sobj) {
    void *pack = malloc(sz);
    if (pack) {
      memcpy(pack, ptr, sz);
      sobj->pack = pack;
      sobj->ty   = ty;
      sobj->size = sz;
    } else {
      sobj = 0;
    }
  }
  rptr = R_MakeExternalPtr(sobj, R_NilValue, R_NilValue); 
  return rptr;
}

SWIGRUNTIME swig_type_info *
RSwigPacked_UnpackData(SEXP obj, void *ptr, size_t size)
{
    RSwigPacked *sobj = 
        (RSwigPacked *)R_ExternalPtrAddr(obj);
    if (sobj->size != size) return 0;
    memcpy(ptr, sobj->pack, size);
    return sobj->ty;
}

SWIGRUNTIMEINLINE SEXP
SWIG_R_NewPackedObj(void *ptr, size_t sz, swig_type_info *type) {
  return ptr ? RSwigPacked_New((void *) ptr, sz, type) : R_NilValue;
}

/* Convert a packed value value */

SWIGRUNTIME int
SWIG_R_ConvertPacked(SEXP obj, void *ptr, size_t sz, swig_type_info *ty) {
  swig_type_info *to = RSwigPacked_UnpackData(obj, ptr, sz);
  if (!to) return SWIG_ERROR;
  if (ty) {
    if (to != ty) {
      /* check type cast? */
      swig_cast_info *tc = SWIG_TypeCheck(to->name,ty);
      if (!tc) return SWIG_ERROR;
    }
  }
  return SWIG_OK;
}  

#ifdef __cplusplus
}
#endif



#define SWIG_exception_fail(code, msg) do { Rf_warning(msg); return Rf_ScalarLogical(NA_LOGICAL); return Rf_ScalarLogical(NA_LOGICAL); } while(0) 

#define SWIG_contract_assert(expr, msg) if (!(expr)) { Rf_warning(msg); return Rf_ScalarLogical(NA_LOGICAL); return Rf_ScalarLogical(NA_LOGICAL); } else 



  #define SWIG_exception(code, msg) do { switch (code) {case SWIG_IndexError: return Rf_ScalarLogical(NA_LOGICAL); default: Rf_warning(msg); return Rf_ScalarLogical(NA_LOGICAL); return Rf_ScalarLogical(NA_LOGICAL);}; } while(0) 


/* -------- TYPES TABLE (BEGIN) -------- */

#define SWIGTYPE_p_MatrixT_bool_t swig_types[0]
#define SWIGTYPE_p_char swig_types[1]
#define SWIGTYPE_p_double swig_types[2]
#define SWIGTYPE_p_int swig_types[3]
static swig_type_info *swig_types[5];
static swig_module_info swig_module = {swig_types, 4, 0, 0, 0, 0};
#define SWIG_TypeQuery(name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MangledTypeQuery(name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)

/* -------- TYPES TABLE (END) -------- */


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif


/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1 
#define  SWIG_IOError        	   -2 
#define  SWIG_RuntimeError   	   -3 
#define  SWIG_IndexError     	   -4 
#define  SWIG_TypeError      	   -5 
#define  SWIG_DivisionByZero 	   -6 
#define  SWIG_OverflowError  	   -7 
#define  SWIG_SyntaxError    	   -8 
#define  SWIG_ValueError     	   -9 
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12 
#define  SWIG_NullReferenceError   -13




#define SWIGVERSION 0x010340 
#define SWIG_VERSION SWIGVERSION


#define SWIG_as_voidptr(a) const_cast< void * >(static_cast< const void * >(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),reinterpret_cast< void** >(a)) 


#include <stdexcept>


#define SWIG_FILE_WITH_INIT
/* !!!!!!!!!!!
*  HACK en attendant une modif de Julien : les sorties sur cerr font segfault
En fait c'est un pb plus general de non init de donnees statiques de la libc++
(on le retrouve avec les exceptions levées par le c++)
il faut mettre -lstdc++ en t^ete des libs au link ou faire LD_PRELOAD=libstdc++.so.6
*/
//#ifdef SWIGR
//#define cerr cout
//#endif
/* !!!! */

#include "spams.h"
#ifdef DEBUG
#include "spams-tst.h"
#endif


extern "C" {
#include <R.h>
#include <Rinternals.h>
#include <Rdefines.h>
#include <R_ext/Rdynload.h>
#include <Rembedded.h>
#include <Rinterface.h>
#include <R_ext/RS.h>
#include <R_ext/Error.h>
}
#include "spams.h"

/* ********************
* this is a hack to handle multiple values outrput
* return value is a vector initailized by swig in typemap out
* R_result_pos is the index in the vector : it must be set to 0 in typemap(out)
* typemap(argout) cannot be used without typemap(ou) in a function
*/

static int R_result_pos = 0;

SEXP appendOutput(SEXP value,SEXP result) {
     R_result_pos++;
     if(LENGTH(result) > R_result_pos)
     	SET_VECTOR_ELT(result,R_result_pos,value);
     return result;
}
/*    end of hack */


#include <limits.h>
#if !defined(SWIG_NO_LLONG_MAX)
# if !defined(LLONG_MAX) && defined(__GNUC__) && defined (__LONG_LONG_MAX__)
#   define LLONG_MAX __LONG_LONG_MAX__
#   define LLONG_MIN (-LLONG_MAX - 1LL)
#   define ULLONG_MAX (LLONG_MAX * 2ULL + 1ULL)
# endif
#endif


SWIGINTERNINLINE  int
SWIG_AsVal_long (SEXP obj, long *val)
{
   if (val) *val = Rf_asInteger(obj);
   return SWIG_OK;
}


SWIGINTERN int
SWIG_AsVal_int (SEXP obj, int *val)
{
  long v;
  int res = SWIG_AsVal_long (obj, &v);
  if (SWIG_IsOK(res)) {
    if ((v < INT_MIN || v > INT_MAX)) {
      return SWIG_OverflowError;
    } else {
      if (val) *val = static_cast< int >(v);
    }
  }  
  return res;
}


SWIGINTERN int
SWIG_AsVal_bool (SEXP obj, bool *val)
{
  long v;
  int res = SWIG_AsVal_long (obj, val ? &v : 0);
  if (SWIG_IsOK(res)) {    
    if (val) *val = v ? true : false;
    return res;
  }  
  return SWIG_TypeError;
}


SWIGINTERNINLINE  int
SWIG_AsVal_double (SEXP obj, double *val)
{
   if (val) *val = Rf_asReal(obj);
   return SWIG_OK;
}


    const int check_sparse(SEXP arg) {
	SEXP ivec = Rf_getAttrib(arg,Rf_install("i"));
	SEXP xvec = Rf_getAttrib(arg,Rf_install("x"));
	SEXP dims = Rf_getAttrib(arg,Rf_install("Dim"));
//	return (Rf_isInteger(ivec) && (TYPEOF(xvec) == R_TYPE) && (LENGTH(dims) == 2) ? 1 : 0);
	return (Rf_isInteger(ivec) && (TYPEOF(xvec) == REALSXP) && (LENGTH(dims) == 2) ? 1 : 0);

    }
    const int check_matrix(SEXP arg) {
    	  SEXP dims = Rf_getAttrib(arg,Rf_install("dim"));
	  return ((TYPEOF(arg) == REALSXP) && (LENGTH(dims) == 2) ? 1 : 0);
    }


SWIGINTERN char *
SWIG_strdup(const char *str)
{
  char *newstr = reinterpret_cast< char * >(malloc(strlen(str) + 1));
  return strcpy(newstr, str);
}


SWIGINTERN int
SWIG_AsCharPtrAndSize(SEXP obj, char** cptr, size_t* psize, int *alloc)
{
  if (cptr && Rf_isString(obj)) {
    const char *cstr = CHAR(STRING_ELT(obj, 0));
    int len = strlen(cstr);

    if (alloc) {
      if (*alloc == SWIG_NEWOBJ) {
        *cptr = reinterpret_cast< char* >(memcpy((new char[len + 1]), cstr, sizeof(char)*(len + 1)));
        *alloc = SWIG_NEWOBJ;
      } else {
        *cptr = reinterpret_cast< char * >(malloc(len + 1));
        *cptr = strcpy(*cptr, cstr);
        *alloc = SWIG_OLDOBJ;
      }
    } else {
      *cptr = reinterpret_cast< char * >(malloc(len + 1));
      *cptr = strcpy(*cptr, cstr);
    }
    if (psize) *psize = len + 1;
    return SWIG_OK;
  }
  return SWIG_TypeError;
}





#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT SEXP
R_swig_multLeftDiag ( SEXP X, SEXP Y, SEXP XY)
{
  Matrix< double > *arg1 = (Matrix< double > *) 0 ;
  Matrix< double > *arg2 = (Matrix< double > *) 0 ;
  Matrix< double > *arg3 = (Matrix< double > *) 0 ;
  unsigned int r_nprotect = 0;
  SEXP r_ans = R_NilValue ;
  VMAXTYPE r_vmax = vmaxget() ;
  
  {
    /*@SWIG:R_typemaps.i,110,map_matrix@*/
    SEXP rmat=X;
    SEXP dims = Rf_getAttrib(rmat,Rf_install("dim"));
    if (TYPEOF(rmat) != REALSXP || LENGTH(dims) != 2)	
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double dense matrix as argument %d",1); return R_NilValue;
      };
    }
    arg1 = new Matrix<double> ((double *)REAL(rmat),Rf_nrows(rmat),Rf_ncols(rmat));
    
    /*@SWIG@*/
  }
  {
    /*@SWIG:R_typemaps.i,110,map_matrix@*/
    SEXP rmat=Y;
    SEXP dims = Rf_getAttrib(rmat,Rf_install("dim"));
    if (TYPEOF(rmat) != REALSXP || LENGTH(dims) != 2)	
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double dense matrix as argument %d",2); return R_NilValue;
      };
    }
    arg2 = new Matrix<double> ((double *)REAL(rmat),Rf_nrows(rmat),Rf_ncols(rmat));
    
    /*@SWIG@*/
  }
  {
    /*@SWIG:R_typemaps.i,110,map_matrix@*/
    SEXP rmat=XY;
    SEXP dims = Rf_getAttrib(rmat,Rf_install("dim"));
    if (TYPEOF(rmat) != REALSXP || LENGTH(dims) != 2)	
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double dense matrix as argument %d",3); return R_NilValue;
      };
    }
    arg3 = new Matrix<double> ((double *)REAL(rmat),Rf_nrows(rmat),Rf_ncols(rmat));
    
    /*@SWIG@*/
  }
  try {
    _multLeftDiag< double >(arg1,arg2,arg3);
  }
  catch(char const *_e) {
    Rf_error("Runtime Error %s",_e); 
    return R_NilValue;
    
  }
  
  r_ans = R_NilValue;
  {
    delete arg1;
  }
  {
    delete arg2;
  }
  {
    delete arg3;
  }
  vmaxset(r_vmax);
  if(r_nprotect)  Rf_unprotect(r_nprotect);
  
  return r_ans;
}

SWIGEXPORT SEXP
R_swig_fistaFlat ( SEXP X, SEXP D, SEXP alpha0, SEXP alpha, SEXP num_threads, SEXP max_it, SEXP L0, SEXP fixed_step, SEXP gamma, SEXP s_lambda, SEXP delta, SEXP lambda2, SEXP lambda3, SEXP a, SEXP b, SEXP c, SEXP tol, SEXP it0, SEXP max_iter_backtracking, SEXP compute_gram, SEXP lin_admm, SEXP admm, SEXP intercept, SEXP resetflow, SEXP name_regul, SEXP name_loss, SEXP verbose, SEXP pos, SEXP clever, SEXP log, SEXP ista, SEXP subgrad, SEXP logName, SEXP is_inner_weights, SEXP inner_weights, SEXP size_group, SEXP sqrt_step, SEXP transpose, SEXP linesearch_mode)
{
  Matrix< double > *result = 0 ;
  Matrix< double > *arg1 = (Matrix< double > *) 0 ;
  AbstractMatrixB< double > *arg2 = (AbstractMatrixB< double > *) 0 ;
  Matrix< double > *arg3 = (Matrix< double > *) 0 ;
  Matrix< double > *arg4 = (Matrix< double > *) 0 ;
  int arg5 ;
  int arg6 ;
  double arg7 ;
  bool arg8 ;
  double arg9 ;
  double arg10 ;
  double arg11 ;
  double arg12 ;
  double arg13 ;
  double arg14 ;
  double arg15 ;
  double arg16 ;
  double arg17 ;
  int arg18 ;
  int arg19 ;
  bool arg20 ;
  bool arg21 ;
  bool arg22 ;
  bool arg23 ;
  bool arg24 ;
  char *arg25 = (char *) 0 ;
  char *arg26 = (char *) 0 ;
  bool arg27 ;
  bool arg28 ;
  bool arg29 ;
  bool arg30 ;
  bool arg31 ;
  bool arg32 ;
  char *arg33 = (char *) 0 ;
  bool arg34 ;
  Vector< double > *arg35 = (Vector< double > *) 0 ;
  int arg36 ;
  bool arg37 ;
  bool arg38 ;
  int arg39 ;
  unsigned int r_nprotect = 0;
  SEXP r_ans = R_NilValue ;
  VMAXTYPE r_vmax = vmaxget() ;
  
  {
    /*@SWIG:R_typemaps.i,110,map_matrix@*/
    SEXP rmat=X;
    SEXP dims = Rf_getAttrib(rmat,Rf_install("dim"));
    if (TYPEOF(rmat) != REALSXP || LENGTH(dims) != 2)	
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double dense matrix as argument %d",1); return R_NilValue;
      };
    }
    arg1 = new Matrix<double> ((double *)REAL(rmat),Rf_nrows(rmat),Rf_ncols(rmat));
    
    /*@SWIG@*/
  }
  {
    SEXP pvec = Rf_getAttrib(D,Rf_install("p"));
    if(pvec ==  R_NilValue) {
      /*@SWIG:R_typemaps.i,110,map_matrix@*/
      SEXP rmat=D;
      SEXP dims = Rf_getAttrib(rmat,Rf_install("dim"));
      if (TYPEOF(rmat) != REALSXP || LENGTH(dims) != 2)	
      {
        /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
        {
          Rf_error("Expected double dense matrix as argument %d",2); return R_NilValue;
        };
      }
      arg2 = new Matrix<double> ((double *)REAL(rmat),Rf_nrows(rmat),Rf_ncols(rmat));
      
      /*@SWIG@*/
    } else {
      /*@SWIG:R_typemaps.i,223,map_sparse@*/
      SEXP spmat=D;
      SEXP ivec = Rf_getAttrib(spmat,Rf_install("i"));
      SEXP pvec = Rf_getAttrib(spmat,Rf_install("p"));
      SEXP xvec = Rf_getAttrib(spmat,Rf_install("x"));
      SEXP dims = Rf_getAttrib(spmat,Rf_install("Dim"));
      
      if (TYPEOF(xvec) != REALSXP || LENGTH(dims) != 2)	
      {
        /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
        {
          Rf_error("Expected double sparse matrix as argument %d",2); return R_NilValue;
        };
      }
      int *pB = INTEGER(pvec);
      int *pE = pB + 1;
      int *idims = INTEGER(dims);
      arg2 = new SpMatrix<double> ((double *)REAL(xvec),INTEGER(ivec),pB,pE,idims[0],idims[1],LENGTH(xvec));
      
      /*@SWIG@*/
    }
  }
  {
    /*@SWIG:R_typemaps.i,110,map_matrix@*/
    SEXP rmat=alpha0;
    SEXP dims = Rf_getAttrib(rmat,Rf_install("dim"));
    if (TYPEOF(rmat) != REALSXP || LENGTH(dims) != 2)	
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double dense matrix as argument %d",3); return R_NilValue;
      };
    }
    arg3 = new Matrix<double> ((double *)REAL(rmat),Rf_nrows(rmat),Rf_ncols(rmat));
    
    /*@SWIG@*/
  }
  {
    /*@SWIG:R_typemaps.i,110,map_matrix@*/
    SEXP rmat=alpha;
    SEXP dims = Rf_getAttrib(rmat,Rf_install("dim"));
    if (TYPEOF(rmat) != REALSXP || LENGTH(dims) != 2)	
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double dense matrix as argument %d",4); return R_NilValue;
      };
    }
    arg4 = new Matrix<double> ((double *)REAL(rmat),Rf_nrows(rmat),Rf_ncols(rmat));
    
    /*@SWIG@*/
  }
  arg5 = static_cast< int >(INTEGER(num_threads)[0]);
  arg6 = static_cast< int >(INTEGER(max_it)[0]);
  arg7 = static_cast< double >(REAL(L0)[0]);
  arg8 = LOGICAL(fixed_step)[0] ? true : false;
  arg9 = static_cast< double >(REAL(gamma)[0]);
  arg10 = static_cast< double >(REAL(s_lambda)[0]);
  arg11 = static_cast< double >(REAL(delta)[0]);
  arg12 = static_cast< double >(REAL(lambda2)[0]);
  arg13 = static_cast< double >(REAL(lambda3)[0]);
  arg14 = static_cast< double >(REAL(a)[0]);
  arg15 = static_cast< double >(REAL(b)[0]);
  arg16 = static_cast< double >(REAL(c)[0]);
  arg17 = static_cast< double >(REAL(tol)[0]);
  arg18 = static_cast< int >(INTEGER(it0)[0]);
  arg19 = static_cast< int >(INTEGER(max_iter_backtracking)[0]);
  arg20 = LOGICAL(compute_gram)[0] ? true : false;
  arg21 = LOGICAL(lin_admm)[0] ? true : false;
  arg22 = LOGICAL(admm)[0] ? true : false;
  arg23 = LOGICAL(intercept)[0] ? true : false;
  arg24 = LOGICAL(resetflow)[0] ? true : false;
  arg25 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(name_regul, 0))));
  arg26 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(name_loss, 0))));
  arg27 = LOGICAL(verbose)[0] ? true : false;
  arg28 = LOGICAL(pos)[0] ? true : false;
  arg29 = LOGICAL(clever)[0] ? true : false;
  arg30 = LOGICAL(log)[0] ? true : false;
  arg31 = LOGICAL(ista)[0] ? true : false;
  arg32 = LOGICAL(subgrad)[0] ? true : false;
  arg33 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(logName, 0))));
  arg34 = LOGICAL(is_inner_weights)[0] ? true : false;
  {
    SEXP rvec=inner_weights;
    if (TYPEOF(rvec) != REALSXP || ! Rf_isVector(rvec))
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double Vector as argument %d",35); return R_NilValue;
      };
    }
    
    arg35 = new Vector<double>((double*) REAL(rvec), LENGTH(rvec));
  }
  arg36 = static_cast< int >(INTEGER(size_group)[0]);
  arg37 = LOGICAL(sqrt_step)[0] ? true : false;
  arg38 = LOGICAL(transpose)[0] ? true : false;
  arg39 = static_cast< int >(INTEGER(linesearch_mode)[0]);
  try {
    result = (Matrix< double > *)_fistaFlat< double >(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15,arg16,arg17,arg18,arg19,arg20,arg21,arg22,arg23,arg24,arg25,arg26,arg27,arg28,arg29,arg30,arg31,arg32,arg33,arg34,arg35,arg36,arg37,arg38,arg39);
  }
  catch(char const *_e) {
    Rf_error("Runtime Error %s",_e); 
    return R_NilValue;
    
  }
  
  {
    R_result_pos = 0;
    R_len_t m = result->m();
    R_len_t n = result->n();
    double *data = result->rawX();
    SEXP rmat;
    PROTECT(rmat = Rf_allocMatrix(REALSXP,m,n));
    if (!rmat) error_return("Cannot alloc R matrix for return value");
    double *rdata = (double *)REAL(rmat);
    memcpy(rdata,data,m * n * sizeof(double));
    delete result;
    r_ans = rmat;
    UNPROTECT(1);
  }
  {
    delete arg1;
  }
  {
    delete arg2;
  }
  {
    delete arg3;
  }
  {
    delete arg4;
  }
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  free(arg25);
  free(arg26);
  
  
  
  
  
  
  free(arg33);
  
  {
    delete arg35;
  }
  
  
  
  
  vmaxset(r_vmax);
  if(r_nprotect)  Rf_unprotect(r_nprotect);
  
  return r_ans;
}


SWIGEXPORT SEXP
R_swig_evalPathCoding ( SEXP alpha0, SEXP dual_val, SEXP precision, SEXP weights, SEXP ir, SEXP jc, SEXP start_weights, SEXP stop_weights, SEXP num_threads, SEXP lambda1, SEXP lambda2, SEXP intercept, SEXP resetflow, SEXP name_regul, SEXP verbose, SEXP pos, SEXP clever, SEXP eval, SEXP eval_dual, SEXP size_group, SEXP transpose)
{
  SpMatrix< double > *result = 0 ;
  Matrix< double > *arg1 = (Matrix< double > *) 0 ;
  Vector< double > *arg2 = (Vector< double > *) 0 ;
  long long arg3 ;
  double *arg4 = (double *) 0 ;
  int *arg5 = (int *) 0 ;
  int *arg6 = (int *) 0 ;
  double *arg7 = (double *) 0 ;
  double *arg8 = (double *) 0 ;
  int arg9 ;
  double arg10 ;
  double arg11 ;
  bool arg12 ;
  bool arg13 ;
  char *arg14 = (char *) 0 ;
  bool arg15 ;
  bool arg16 ;
  bool arg17 ;
  bool arg18 ;
  bool arg19 ;
  int arg20 ;
  bool arg21 ;
  long val3 ;
  int ecode3 = 0 ;
  unsigned int r_nprotect = 0;
  SEXP r_ans = R_NilValue ;
  VMAXTYPE r_vmax = vmaxget() ;
  
  {
    /*@SWIG:R_typemaps.i,110,map_matrix@*/
    SEXP rmat=alpha0;
    SEXP dims = Rf_getAttrib(rmat,Rf_install("dim"));
    if (TYPEOF(rmat) != REALSXP || LENGTH(dims) != 2)	
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double dense matrix as argument %d",1); return R_NilValue;
      };
    }
    arg1 = new Matrix<double> ((double *)REAL(rmat),Rf_nrows(rmat),Rf_ncols(rmat));
    
    /*@SWIG@*/
  }
  {
    SEXP rvec=dual_val;
    if (TYPEOF(rvec) != REALSXP || ! Rf_isVector(rvec))
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double Vector as argument %d",2); return R_NilValue;
      };
    }
    
    arg2 = new Vector<double>((double*) REAL(rvec), LENGTH(rvec));
  }
  ecode3 = SWIG_AsVal_long(precision, &val3);
  if (!SWIG_IsOK(ecode3)) {
    SWIG_exception_fail(SWIG_ArgError(ecode3), "in method '" "evalPathCoding" "', argument " "3"" of type '" "long long""'");
  } 
  arg3 = static_cast< long long >(val3);
  {
    {
      int _rswigi;
      int _rswiglen = LENGTH(weights);
      arg4 = static_cast< double * >(calloc(sizeof(double), _rswiglen));
      for (_rswigi=0; _rswigi<_rswiglen; _rswigi++) {
        arg4[_rswigi] = REAL(weights)[_rswigi];
      }
    }
  }
  {
    {
      int _rswigi;
      int _rswiglen = LENGTH(ir);
      arg5 = static_cast< int * >(calloc(sizeof(int), _rswiglen));
      for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
        arg5[_rswigi] = INTEGER(ir)[_rswigi];
      }
    }
  }
  {
    {
      int _rswigi;
      int _rswiglen = LENGTH(jc);
      arg6 = static_cast< int * >(calloc(sizeof(int), _rswiglen));
      for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
        arg6[_rswigi] = INTEGER(jc)[_rswigi];
      }
    }
  }
  {
    {
      int _rswigi;
      int _rswiglen = LENGTH(start_weights);
      arg7 = static_cast< double * >(calloc(sizeof(double), _rswiglen));
      for (_rswigi=0; _rswigi<_rswiglen; _rswigi++) {
        arg7[_rswigi] = REAL(start_weights)[_rswigi];
      }
    }
  }
  {
    {
      int _rswigi;
      int _rswiglen = LENGTH(stop_weights);
      arg8 = static_cast< double * >(calloc(sizeof(double), _rswiglen));
      for (_rswigi=0; _rswigi<_rswiglen; _rswigi++) {
        arg8[_rswigi] = REAL(stop_weights)[_rswigi];
      }
    }
  }
  arg9 = static_cast< int >(INTEGER(num_threads)[0]);
  arg10 = static_cast< double >(REAL(lambda1)[0]);
  arg11 = static_cast< double >(REAL(lambda2)[0]);
  arg12 = LOGICAL(intercept)[0] ? true : false;
  arg13 = LOGICAL(resetflow)[0] ? true : false;
  arg14 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(name_regul, 0))));
  arg15 = LOGICAL(verbose)[0] ? true : false;
  arg16 = LOGICAL(pos)[0] ? true : false;
  arg17 = LOGICAL(clever)[0] ? true : false;
  arg18 = LOGICAL(eval)[0] ? true : false;
  arg19 = LOGICAL(eval_dual)[0] ? true : false;
  arg20 = static_cast< int >(INTEGER(size_group)[0]);
  arg21 = LOGICAL(transpose)[0] ? true : false;
  try {
    result = (SpMatrix< double > *)_evalPathCoding< double >(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15,arg16,arg17,arg18,arg19,arg20,arg21);
  }
  catch(char const *_e) {
    Rf_error("Runtime Error %s",_e); 
    return R_NilValue;
    
  }
  
  {
    R_result_pos = 0;
    R_len_t m = result->m();
    R_len_t n = result->n();
    SEXP indptr, indices, vdata, dims, output;
    PROTECT(indptr = Rf_allocVector(INTSXP,n + 1));
    PROTECT(dims = Rf_allocVector(VECSXP,2));
    SET_VECTOR_ELT(dims,0,Rf_ScalarInteger(m));
    SET_VECTOR_ELT(dims,1,Rf_ScalarInteger(n));    
    
    double *xdata = result->v();
    int *pB = result->pB();
    int *r = result->r();
    
    PROTECT(indices = Rf_allocVector(INTSXP,pB[n]));
    PROTECT(vdata = Rf_allocVector(REALSXP,pB[n]));
    memcpy(REAL(vdata),xdata,pB[n] * sizeof(double));
    memcpy(INTEGER(indices),r,pB[n] * sizeof(int));
    memcpy(INTEGER(indptr),pB,(n + 1) * sizeof(int));
    
    PROTECT(output = Rf_allocVector(VECSXP,4));
    SET_VECTOR_ELT(output,0,indptr);
    SET_VECTOR_ELT(output,1,indices);
    SET_VECTOR_ELT(output,2,vdata);
    SET_VECTOR_ELT(output,3,dims);
    delete result;
    r_ans = output;
    UNPROTECT(5);
  }
  {
    delete arg1;
  }
  {
    delete arg2;
  }
  
  
  free(arg4);
  
  
  free(arg5);
  
  
  free(arg6);
  
  
  free(arg7);
  
  
  free(arg8);
  
  
  
  
  
  
  free(arg14);
  
  
  
  
  
  
  
  vmaxset(r_vmax);
  if(r_nprotect)  Rf_unprotect(r_nprotect);
  
  return r_ans;
}


SWIGEXPORT SEXP
R_swig_sepCostsPathCoding ( SEXP alpha0, SEXP alpha, SEXP weights, SEXP ir, SEXP jc, SEXP start_weights, SEXP stop_weights, SEXP max_capacity, SEXP epsilon_flow, SEXP prices, SEXP num_threads, SEXP lambda, SEXP tol, SEXP delta, SEXP loss_weights, SEXP name_regul, SEXP name_loss, SEXP pos, SEXP mode_decomposition)
{
  SpMatrix< double > *result = 0 ;
  Matrix< double > *arg1 = (Matrix< double > *) 0 ;
  Matrix< double > *arg2 = (Matrix< double > *) 0 ;
  double *arg3 = (double *) 0 ;
  int *arg4 = (int *) 0 ;
  int *arg5 = (int *) 0 ;
  double *arg6 = (double *) 0 ;
  double *arg7 = (double *) 0 ;
  double arg8 ;
  double arg9 ;
  Vector< double > *arg10 = (Vector< double > *) 0 ;
  int arg11 ;
  double arg12 ;
  double arg13 ;
  double arg14 ;
  double *arg15 = (double *) 0 ;
  char *arg16 = (char *) 0 ;
  char *arg17 = (char *) 0 ;
  bool arg18 ;
  int arg19 ;
  unsigned int r_nprotect = 0;
  SEXP r_ans = R_NilValue ;
  VMAXTYPE r_vmax = vmaxget() ;
  
  {
    /*@SWIG:R_typemaps.i,110,map_matrix@*/
    SEXP rmat=alpha0;
    SEXP dims = Rf_getAttrib(rmat,Rf_install("dim"));
    if (TYPEOF(rmat) != REALSXP || LENGTH(dims) != 2)	
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double dense matrix as argument %d",1); return R_NilValue;
      };
    }
    arg1 = new Matrix<double> ((double *)REAL(rmat),Rf_nrows(rmat),Rf_ncols(rmat));
    
    /*@SWIG@*/
  }
  {
    /*@SWIG:R_typemaps.i,110,map_matrix@*/
    SEXP rmat=alpha;
    SEXP dims = Rf_getAttrib(rmat,Rf_install("dim"));
    if (TYPEOF(rmat) != REALSXP || LENGTH(dims) != 2)	
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double dense matrix as argument %d",2); return R_NilValue;
      };
    }
    arg2 = new Matrix<double> ((double *)REAL(rmat),Rf_nrows(rmat),Rf_ncols(rmat));
    
    /*@SWIG@*/
  }
  {
    {
      int _rswigi;
      int _rswiglen = LENGTH(weights);
      arg3 = static_cast< double * >(calloc(sizeof(double), _rswiglen));
      for (_rswigi=0; _rswigi<_rswiglen; _rswigi++) {
        arg3[_rswigi] = REAL(weights)[_rswigi];
      }
    }
  }
  {
    {
      int _rswigi;
      int _rswiglen = LENGTH(ir);
      arg4 = static_cast< int * >(calloc(sizeof(int), _rswiglen));
      for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
        arg4[_rswigi] = INTEGER(ir)[_rswigi];
      }
    }
  }
  {
    {
      int _rswigi;
      int _rswiglen = LENGTH(jc);
      arg5 = static_cast< int * >(calloc(sizeof(int), _rswiglen));
      for (_rswigi=0; _rswigi< _rswiglen; _rswigi++) {
        arg5[_rswigi] = INTEGER(jc)[_rswigi];
      }
    }
  }
  {
    {
      int _rswigi;
      int _rswiglen = LENGTH(start_weights);
      arg6 = static_cast< double * >(calloc(sizeof(double), _rswiglen));
      for (_rswigi=0; _rswigi<_rswiglen; _rswigi++) {
        arg6[_rswigi] = REAL(start_weights)[_rswigi];
      }
    }
  }
  {
    {
      int _rswigi;
      int _rswiglen = LENGTH(stop_weights);
      arg7 = static_cast< double * >(calloc(sizeof(double), _rswiglen));
      for (_rswigi=0; _rswigi<_rswiglen; _rswigi++) {
        arg7[_rswigi] = REAL(stop_weights)[_rswigi];
      }
    }
  }
  arg8 = static_cast< double >(REAL(max_capacity)[0]);
  arg9 = static_cast< double >(REAL(epsilon_flow)[0]);
  {
    SEXP rvec=prices;
    if (TYPEOF(rvec) != REALSXP || ! Rf_isVector(rvec))
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double Vector as argument %d",10); return R_NilValue;
      };
    }
    
    arg10 = new Vector<double>((double*) REAL(rvec), LENGTH(rvec));
  }
  arg11 = static_cast< int >(INTEGER(num_threads)[0]);
  arg12 = static_cast< double >(REAL(lambda)[0]);
  arg13 = static_cast< double >(REAL(tol)[0]);
  arg14 = static_cast< double >(REAL(delta)[0]);
  {
    {
      int _rswigi;
      int _rswiglen = LENGTH(loss_weights);
      arg15 = static_cast< double * >(calloc(sizeof(double), _rswiglen));
      for (_rswigi=0; _rswigi<_rswiglen; _rswigi++) {
        arg15[_rswigi] = REAL(loss_weights)[_rswigi];
      }
    }
  }
  arg16 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(name_regul, 0))));
  arg17 = reinterpret_cast< char * >(SWIG_strdup(CHAR(STRING_ELT(name_loss, 0))));
  arg18 = LOGICAL(pos)[0] ? true : false;
  arg19 = static_cast< int >(INTEGER(mode_decomposition)[0]);
  try {
    result = (SpMatrix< double > *)_sepCostsPathCoding< double >(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15,arg16,arg17,arg18,arg19);
  }
  catch(char const *_e) {
    Rf_error("Runtime Error %s",_e); 
    return R_NilValue;
    
  }
  
  {
    R_result_pos = 0;
    R_len_t m = result->m();
    R_len_t n = result->n();
    SEXP indptr, indices, vdata, dims, output;
    PROTECT(indptr = Rf_allocVector(INTSXP,n + 1));
    PROTECT(dims = Rf_allocVector(VECSXP,2));
    SET_VECTOR_ELT(dims,0,Rf_ScalarInteger(m));
    SET_VECTOR_ELT(dims,1,Rf_ScalarInteger(n));    
    
    double *xdata = result->v();
    int *pB = result->pB();
    int *r = result->r();
    
    PROTECT(indices = Rf_allocVector(INTSXP,pB[n]));
    PROTECT(vdata = Rf_allocVector(REALSXP,pB[n]));
    memcpy(REAL(vdata),xdata,pB[n] * sizeof(double));
    memcpy(INTEGER(indices),r,pB[n] * sizeof(int));
    memcpy(INTEGER(indptr),pB,(n + 1) * sizeof(int));
    
    PROTECT(output = Rf_allocVector(VECSXP,4));
    SET_VECTOR_ELT(output,0,indptr);
    SET_VECTOR_ELT(output,1,indices);
    SET_VECTOR_ELT(output,2,vdata);
    SET_VECTOR_ELT(output,3,dims);
    delete result;
    r_ans = output;
    UNPROTECT(5);
  }
  {
    delete arg1;
  }
  {
    delete arg2;
  }
  
  free(arg3);
  
  
  free(arg4);
  
  
  free(arg5);
  
  
  free(arg6);
  
  
  free(arg7);
  
  
  
  {
    delete arg10;
  }
  
  
  
  
  
  free(arg15);
  
  free(arg16);
  free(arg17);
  
  
  vmaxset(r_vmax);
  if(r_nprotect)  Rf_unprotect(r_nprotect);
  
  return r_ans;
}


SWIGEXPORT SEXP
R_swig_solverPoisson ( SEXP y, SEXP X, SEXP beta0, SEXP beta, SEXP weights, SEXP delta, SEXP max_iter, SEXP tol)
{
  Vector< double > *arg1 = (Vector< double > *) 0 ;
  SpMatrix< double > *arg2 = (SpMatrix< double > *) 0 ;
  Vector< double > *arg3 = (Vector< double > *) 0 ;
  Vector< double > *arg4 = (Vector< double > *) 0 ;
  Vector< double > *arg5 = (Vector< double > *) 0 ;
  double arg6 ;
  int arg7 ;
  double arg8 ;
  unsigned int r_nprotect = 0;
  SEXP r_ans = R_NilValue ;
  VMAXTYPE r_vmax = vmaxget() ;
  
  {
    SEXP rvec=y;
    if (TYPEOF(rvec) != REALSXP || ! Rf_isVector(rvec))
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double Vector as argument %d",1); return R_NilValue;
      };
    }
    
    arg1 = new Vector<double>((double*) REAL(rvec), LENGTH(rvec));
  }
  {
    /*@SWIG:R_typemaps.i,223,map_sparse@*/
    SEXP spmat=X;
    SEXP ivec = Rf_getAttrib(spmat,Rf_install("i"));
    SEXP pvec = Rf_getAttrib(spmat,Rf_install("p"));
    SEXP xvec = Rf_getAttrib(spmat,Rf_install("x"));
    SEXP dims = Rf_getAttrib(spmat,Rf_install("Dim"));
    
    if (TYPEOF(xvec) != REALSXP || LENGTH(dims) != 2)	
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double sparse matrix as argument %d",2); return R_NilValue;
      };
    }
    int *pB = INTEGER(pvec);
    int *pE = pB + 1;
    int *idims = INTEGER(dims);
    arg2 = new SpMatrix<double> ((double *)REAL(xvec),INTEGER(ivec),pB,pE,idims[0],idims[1],LENGTH(xvec));
    
    /*@SWIG@*/
  }
  {
    SEXP rvec=beta0;
    if (TYPEOF(rvec) != REALSXP || ! Rf_isVector(rvec))
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double Vector as argument %d",3); return R_NilValue;
      };
    }
    
    arg3 = new Vector<double>((double*) REAL(rvec), LENGTH(rvec));
  }
  {
    SEXP rvec=beta;
    if (TYPEOF(rvec) != REALSXP || ! Rf_isVector(rvec))
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double Vector as argument %d",4); return R_NilValue;
      };
    }
    
    arg4 = new Vector<double>((double*) REAL(rvec), LENGTH(rvec));
  }
  {
    SEXP rvec=weights;
    if (TYPEOF(rvec) != REALSXP || ! Rf_isVector(rvec))
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double Vector as argument %d",5); return R_NilValue;
      };
    }
    
    arg5 = new Vector<double>((double*) REAL(rvec), LENGTH(rvec));
  }
  arg6 = static_cast< double >(REAL(delta)[0]);
  arg7 = static_cast< int >(INTEGER(max_iter)[0]);
  arg8 = static_cast< double >(REAL(tol)[0]);
  try {
    _solverPoisson< double >(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  }
  catch(char const *_e) {
    Rf_error("Runtime Error %s",_e); 
    return R_NilValue;
    
  }
  
  r_ans = R_NilValue;
  {
    delete arg1;
  }
  {
    delete arg2;
  }
  {
    delete arg3;
  }
  {
    delete arg4;
  }
  {
    delete arg5;
  }
  
  
  
  vmaxset(r_vmax);
  if(r_nprotect)  Rf_unprotect(r_nprotect);
  
  return r_ans;
}


SWIGEXPORT SEXP
R_swig_solverPoissonFull ( SEXP y, SEXP X, SEXP beta0, SEXP beta, SEXP weights, SEXP delta, SEXP max_iter, SEXP tol)
{
  Vector< double > *arg1 = (Vector< double > *) 0 ;
  Matrix< double > *arg2 = (Matrix< double > *) 0 ;
  Vector< double > *arg3 = (Vector< double > *) 0 ;
  Vector< double > *arg4 = (Vector< double > *) 0 ;
  Vector< double > *arg5 = (Vector< double > *) 0 ;
  double arg6 ;
  int arg7 ;
  double arg8 ;
  unsigned int r_nprotect = 0;
  SEXP r_ans = R_NilValue ;
  VMAXTYPE r_vmax = vmaxget() ;
  
  {
    SEXP rvec=y;
    if (TYPEOF(rvec) != REALSXP || ! Rf_isVector(rvec))
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double Vector as argument %d",1); return R_NilValue;
      };
    }
    
    arg1 = new Vector<double>((double*) REAL(rvec), LENGTH(rvec));
  }
  {
    /*@SWIG:R_typemaps.i,110,map_matrix@*/
    SEXP rmat=X;
    SEXP dims = Rf_getAttrib(rmat,Rf_install("dim"));
    if (TYPEOF(rmat) != REALSXP || LENGTH(dims) != 2)	
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double dense matrix as argument %d",2); return R_NilValue;
      };
    }
    arg2 = new Matrix<double> ((double *)REAL(rmat),Rf_nrows(rmat),Rf_ncols(rmat));
    
    /*@SWIG@*/
  }
  {
    SEXP rvec=beta0;
    if (TYPEOF(rvec) != REALSXP || ! Rf_isVector(rvec))
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double Vector as argument %d",3); return R_NilValue;
      };
    }
    
    arg3 = new Vector<double>((double*) REAL(rvec), LENGTH(rvec));
  }
  {
    SEXP rvec=beta;
    if (TYPEOF(rvec) != REALSXP || ! Rf_isVector(rvec))
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double Vector as argument %d",4); return R_NilValue;
      };
    }
    
    arg4 = new Vector<double>((double*) REAL(rvec), LENGTH(rvec));
  }
  {
    SEXP rvec=weights;
    if (TYPEOF(rvec) != REALSXP || ! Rf_isVector(rvec))
    {
      /*SG_ERROR("Expected Double Vector as argument %d\n", m_rhs_counter);*/
      {
        Rf_error("Expected double Vector as argument %d",5); return R_NilValue;
      };
    }
    
    arg5 = new Vector<double>((double*) REAL(rvec), LENGTH(rvec));
  }
  arg6 = static_cast< double >(REAL(delta)[0]);
  arg7 = static_cast< int >(INTEGER(max_iter)[0]);
  arg8 = static_cast< double >(REAL(tol)[0]);
  try {
    _solverPoissonFull< double >(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  }
  catch(char const *_e) {
    Rf_error("Runtime Error %s",_e); 
    return R_NilValue;
    
  }
  
  r_ans = R_NilValue;
  {
    delete arg1;
  }
  {
    delete arg2;
  }
  {
    delete arg3;
  }
  {
    delete arg4;
  }
  {
    delete arg5;
  }
  
  
  
  vmaxset(r_vmax);
  if(r_nprotect)  Rf_unprotect(r_nprotect);
  
  return r_ans;
}


#ifdef __cplusplus
}
#endif

/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_MatrixT_bool_t = {"_p_MatrixT_bool_t", "Matrix< bool > *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_char = {"_p_char", "char *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_double = {"_p_double", "double *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_int = {"_p_int", "int *", 0, 0, (void*)0, 0};

static swig_type_info *swig_type_initial[] = {
  &_swigt__p_MatrixT_bool_t,
  &_swigt__p_char,
  &_swigt__p_double,
  &_swigt__p_int,
};

static swig_cast_info _swigc__p_MatrixT_bool_t[] = {  {&_swigt__p_MatrixT_bool_t, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_char[] = {  {&_swigt__p_char, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_double[] = {  {&_swigt__p_double, 0, 0, 0},{0, 0, 0, 0}};
static swig_cast_info _swigc__p_int[] = {  {&_swigt__p_int, 0, 0, 0},{0, 0, 0, 0}};

static swig_cast_info *swig_cast_initial[] = {
  _swigc__p_MatrixT_bool_t,
  _swigc__p_char,
  _swigc__p_double,
  _swigc__p_int,
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */


/* -----------------------------------------------------------------------------
 * Type initialization:
 * This problem is tough by the requirement that no dynamic 
 * memory is used. Also, since swig_type_info structures store pointers to 
 * swig_cast_info structures and swig_cast_info structures store pointers back
 * to swig_type_info structures, we need some lookup code at initialization. 
 * The idea is that swig generates all the structures that are needed. 
 * The runtime then collects these partially filled structures. 
 * The SWIG_InitializeModule function takes these initial arrays out of 
 * swig_module, and does all the lookup, filling in the swig_module.types
 * array with the correct data and linking the correct swig_cast_info
 * structures together.
 *
 * The generated swig_type_info structures are assigned staticly to an initial 
 * array. We just loop through that array, and handle each type individually.
 * First we lookup if this type has been already loaded, and if so, use the
 * loaded structure instead of the generated one. Then we have to fill in the
 * cast linked list. The cast data is initially stored in something like a
 * two-dimensional array. Each row corresponds to a type (there are the same
 * number of rows as there are in the swig_type_initial array). Each entry in
 * a column is one of the swig_cast_info structures for that type.
 * The cast_initial array is actually an array of arrays, because each row has
 * a variable number of columns. So to actually build the cast linked list,
 * we find the array of casts associated with the type, and loop through it 
 * adding the casts to the list. The one last trick we need to do is making
 * sure the type pointer in the swig_cast_info struct is correct.
 *
 * First off, we lookup the cast->type name to see if it is already loaded. 
 * There are three cases to handle:
 *  1) If the cast->type has already been loaded AND the type we are adding
 *     casting info to has not been loaded (it is in this module), THEN we
 *     replace the cast->type pointer with the type pointer that has already
 *     been loaded.
 *  2) If BOTH types (the one we are adding casting info to, and the 
 *     cast->type) are loaded, THEN the cast info has already been loaded by
 *     the previous module so we just ignore it.
 *  3) Finally, if cast->type has not already been loaded, then we add that
 *     swig_cast_info to the linked list (because the cast->type) pointer will
 *     be correct.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
extern "C" {
#if 0
} /* c-mode */
#endif
#endif

#if 0
#define SWIGRUNTIME_DEBUG
#endif


SWIGRUNTIME void
SWIG_InitializeModule(void *clientdata) {
  size_t i;
  swig_module_info *module_head, *iter;
  int found, init;

  clientdata = clientdata;

  /* check to see if the circular list has been setup, if not, set it up */
  if (swig_module.next==0) {
    /* Initialize the swig_module */
    swig_module.type_initial = swig_type_initial;
    swig_module.cast_initial = swig_cast_initial;
    swig_module.next = &swig_module;
    init = 1;
  } else {
    init = 0;
  }

  /* Try and load any already created modules */
  module_head = SWIG_GetModule(clientdata);
  if (!module_head) {
    /* This is the first module loaded for this interpreter */
    /* so set the swig module into the interpreter */
    SWIG_SetModule(clientdata, &swig_module);
    module_head = &swig_module;
  } else {
    /* the interpreter has loaded a SWIG module, but has it loaded this one? */
    found=0;
    iter=module_head;
    do {
      if (iter==&swig_module) {
        found=1;
        break;
      }
      iter=iter->next;
    } while (iter!= module_head);

    /* if the is found in the list, then all is done and we may leave */
    if (found) return;
    /* otherwise we must add out module into the list */
    swig_module.next = module_head->next;
    module_head->next = &swig_module;
  }

  /* When multiple interpeters are used, a module could have already been initialized in
     a different interpreter, but not yet have a pointer in this interpreter.
     In this case, we do not want to continue adding types... everything should be
     set up already */
  if (init == 0) return;

  /* Now work on filling in swig_module.types */
#ifdef SWIGRUNTIME_DEBUG
  printf("SWIG_InitializeModule: size %d\n", swig_module.size);
#endif
  for (i = 0; i < swig_module.size; ++i) {
    swig_type_info *type = 0;
    swig_type_info *ret;
    swig_cast_info *cast;
  
#ifdef SWIGRUNTIME_DEBUG
    printf("SWIG_InitializeModule: type %d %s\n", i, swig_module.type_initial[i]->name);
#endif

    /* if there is another module already loaded */
    if (swig_module.next != &swig_module) {
      type = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, swig_module.type_initial[i]->name);
    }
    if (type) {
      /* Overwrite clientdata field */
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: found type %s\n", type->name);
#endif
      if (swig_module.type_initial[i]->clientdata) {
	type->clientdata = swig_module.type_initial[i]->clientdata;
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: found and overwrite type %s \n", type->name);
#endif
      }
    } else {
      type = swig_module.type_initial[i];
    }

    /* Insert casting types */
    cast = swig_module.cast_initial[i];
    while (cast->type) {
    
      /* Don't need to add information already in the list */
      ret = 0;
#ifdef SWIGRUNTIME_DEBUG
      printf("SWIG_InitializeModule: look cast %s\n", cast->type->name);
#endif
      if (swig_module.next != &swig_module) {
        ret = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, cast->type->name);
#ifdef SWIGRUNTIME_DEBUG
	if (ret) printf("SWIG_InitializeModule: found cast %s\n", ret->name);
#endif
      }
      if (ret) {
	if (type == swig_module.type_initial[i]) {
#ifdef SWIGRUNTIME_DEBUG
	  printf("SWIG_InitializeModule: skip old type %s\n", ret->name);
#endif
	  cast->type = ret;
	  ret = 0;
	} else {
	  /* Check for casting already in the list */
	  swig_cast_info *ocast = SWIG_TypeCheck(ret->name, type);
#ifdef SWIGRUNTIME_DEBUG
	  if (ocast) printf("SWIG_InitializeModule: skip old cast %s\n", ret->name);
#endif
	  if (!ocast) ret = 0;
	}
      }

      if (!ret) {
#ifdef SWIGRUNTIME_DEBUG
	printf("SWIG_InitializeModule: adding cast %s\n", cast->type->name);
#endif
        if (type->cast) {
          type->cast->prev = cast;
          cast->next = type->cast;
        }
        type->cast = cast;
      }
      cast++;
    }
    /* Set entry in modules->types array equal to the type */
    swig_module.types[i] = type;
  }
  swig_module.types[i] = 0;

#ifdef SWIGRUNTIME_DEBUG
  printf("**** SWIG_InitializeModule: Cast List ******\n");
  for (i = 0; i < swig_module.size; ++i) {
    int j = 0;
    swig_cast_info *cast = swig_module.cast_initial[i];
    printf("SWIG_InitializeModule: type %d %s\n", i, swig_module.type_initial[i]->name);
    while (cast->type) {
      printf("SWIG_InitializeModule: cast type %s\n", cast->type->name);
      cast++;
      ++j;
    }
  printf("---- Total casts: %d\n",j);
  }
  printf("**** SWIG_InitializeModule: Cast List ******\n");
#endif
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
SWIGRUNTIME void
SWIG_PropagateClientData(void) {
  size_t i;
  swig_cast_info *equiv;
  static int init_run = 0;

  if (init_run) return;
  init_run = 1;

  for (i = 0; i < swig_module.size; i++) {
    if (swig_module.types[i]->clientdata) {
      equiv = swig_module.types[i]->cast;
      while (equiv) {
        if (!equiv->converter) {
          if (equiv->type && !equiv->type->clientdata)
            SWIG_TypeClientData(equiv->type, swig_module.types[i]->clientdata);
        }
        equiv = equiv->next;
      }
    }
  }
}

#ifdef __cplusplus
#if 0
{ /* c-mode */
#endif
}
#endif


SWIGEXPORT void SWIG_init(void) {

}
#ifdef __cplusplus
extern "C" {
#endif

#include <R_ext/Rdynload.h>

#ifdef __cplusplus
}
#endif

SWIGINTERN R_CallMethodDef CallEntries[] = {
   {"R_swig_multLeftDiag", (DL_FUNC) &R_swig_multLeftDiag, 3},
   {"R_swig_fistaFlat", (DL_FUNC) &R_swig_fistaFlat, 39},
   {"R_swig_solverPoissonFull", (DL_FUNC) &R_swig_solverPoissonFull, 8},
   {"R_swig_evalPathCoding", (DL_FUNC) &R_swig_evalPathCoding, 21},
   {"R_swig_sepCostsPathCoding", (DL_FUNC) &R_swig_sepCostsPathCoding, 19},
   {"R_swig_solverPoisson", (DL_FUNC) &R_swig_solverPoisson, 8},
   {NULL, NULL, 0}
};

extern "C" SWIGEXPORT void R_init_spams(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);


SWIG_init();
SWIG_InitializeModule(0);


}

